name: Java CI with Maven and Docker

on:
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'adopt'
    - name: Build with Maven
      working-directory: ./META-INF/maven/com.helloworld/web
      run: mvn -B package --file pom.xml
    - name: Build Docker image
      working-directory: ./META-INF/maven/com.helloworld/web
      run: |
        docker build -t my-app --build-arg JAR_FILE=target/application-0.0.1-SNAPSHOT.jar .

    - name: run docker image
      run: |
        docker run -p 8080:8080 my-app
        
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-app-jar
        path: target/application-0.0.1-SNAPSHOT.jar
